// Package pages writes the static orientation pages into the atlas vault.
package pages

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/nathanaday/claude-atlas/internal/home"
)

// Repository is the project's home on GitHub.
const Repository = "https://github.com/nathanaday/claude-atlas"

const about = `# About

> [!info] Orientation
> This vault is your atlas: one place that looks across every claude-obsidian vault you keep. claude-atlas generates and maintains it. Source and issues: %REPO%

## What is here

| Page | What it is |
|:--|:--|
| [[Overview]] | The view. Every vault, its heat and idle time, open threads, unfinished work, and your declared priority, side by side. Regenerated by ` + "`claude-atlas refresh`" + `. |
| [[Reference]] | Every ` + "`claude-atlas`" + ` command with examples. |
| ` + "`tree/`" + ` | Your projects. Every markdown file is a project; every folder is a category. Arrange them however you think. |

## How it fits together

| Piece | Where | Who writes it |
|:--|:--|:--|
| Your vaults | %VAULTS% | claude-obsidian, through Claude Code |
| This atlas | %ATLAS% | You, in ` + "`tree/`" + `; claude-atlas writes [[Overview]], [[About]], and [[Reference]] |
| Settings and derived state | %HOME% | claude-atlas. Derived state is rebuilt on every refresh and safe to delete. |

> [!tip] Three rules
> The atlas never writes into a vault. A vault never learns the atlas exists. The atlas never stores a fact it can compute; derived state and [[Overview]] are rebuilt from scratch on every refresh.

## The tree

` + "```" + `
tree/
├── university/
│   └── cs566/
│       ├── capstone.md
│       └── course-material.md
└── personal/
    └── reading-list.md
` + "```" + `

Folders are categories and carry no data of their own; make, rename, and nest them freely. Each markdown file is one project that points at one vault. Move a project by moving its file, then run ` + "`claude-atlas refresh`" + `.

## Editing a project

Open its page under ` + "`tree/`" + `. The properties panel shows the fields the atlas reads:

| Property | Values | Meaning |
|:--|:--|:--|
| vault | a path | The claude-obsidian vault this project tracks. Required. |
| priority | high, normal, low, someday | What you intend, not what you did. |
| state | active, paused, blocked, archived | Where the project stands. |
| blocked_on | free text | What you are waiting for, when state is blocked. |
| review_after | a date | When to revisit these fields. Overview flags it once it passes. |
| purpose, definition_of_done | free text | Why this exists and what finished looks like. |

The body below the properties is yours. Keep notes there that belong to the atlas rather than to the vault.

To add a project by hand, create a markdown file under ` + "`tree/`" + ` with this frontmatter, then refresh:

` + "```yaml" + `
---
schema: atlas.project.v1
vault: /path/to/the/vault
priority: normal
state: active
---
` + "```" + `

Run ` + "`claude-atlas refresh`" + ` after any edit to update [[Overview]].
`

const reference = `# Reference

> [!info] Generated page
> ` + "`claude-atlas`" + ` writes this page on every refresh so it matches the installed version (%VERSION%).

## Setup

Install claude-obsidian into Claude Code, create the atlas, and create a first vault. Safe to run again; finished steps are skipped.

` + "```bash" + `
claude-atlas setup
claude-atlas setup --atlas-vault ~/Documents/Atlas --vaults-dir ~/Documents/Vaults
claude-atlas setup --first-vault research
claude-atlas setup --no-plugin        # skip the claude plugin step
claude-atlas -y setup                 # answer yes to every prompt
` + "```" + `

## Vaults

Create a vault. A bare name lands in the vaults directory; a path is used as given. The plan is shown and applied after one confirmation.

` + "```bash" + `
claude-atlas vault new sensor-triage
claude-atlas vault new sensor-triage --category work
claude-atlas vault new sensor-triage --purpose "Sort field sensor faults." --priority high
claude-atlas vault new ~/Desktop/scratch-vault
` + "```" + `

Register a claude-obsidian vault that already exists.

` + "```bash" + `
claude-atlas vault add ~/Documents/OldVault
claude-atlas vault add ~/Documents/OldVault --name "Old Vault" --category archive --priority someday
` + "```" + `

List registered vaults with their heat, priority, and state.

` + "```bash" + `
claude-atlas vault list
` + "```" + `

## Refresh

Read every vault and rewrite [[Overview]] and the derived state. Read-only toward the vaults.

` + "```bash" + `
claude-atlas refresh
` + "```" + `

## Inspect

` + "```bash" + `
claude-atlas info      # every path and version the atlas uses
claude-atlas doctor    # check the installation and reach every vault
claude-atlas version
` + "```" + `

## Options and environment

| Flag or variable | Effect |
|:--|:--|
| ` + "`--home DIR`" + ` | Use a different home instead of ` + "`~/.claude-atlas`" + `. |
| ` + "`-y`, `--yes`" + ` | Answer yes to every prompt. |
| ` + "`CLAUDE_ATLAS_HOME`" + ` | Same as ` + "`--home`" + `. |
| ` + "`claude_obsidian.path`" + ` in config.json | Use a claude-obsidian checkout instead of the installed plugin. |

## Working in a vault

` + "```bash" + `
cd ~/Documents/Vaults/sensor-triage
claude
# then, inside Claude Code:
/claude-obsidian:wiki
` + "```" + `

## Moving a project

The tree is plain files and folders. Move the file, then refresh.

` + "```bash" + `
mv ~/Documents/Atlas/tree/sensor-triage.md ~/Documents/Atlas/tree/work/
claude-atlas refresh
` + "```" + `
`

// Write renders About.md and Reference.md into the atlas vault.
func Write(cfg *home.Config, homeRoot, version string) error {
	r := strings.NewReplacer(
		"%REPO%", Repository,
		"%VERSION%", version,
		"%VAULTS%", "`"+home.Display(cfg.VaultsDir)+"`",
		"%ATLAS%", "`"+home.Display(cfg.AtlasVault)+"`",
		"%HOME%", "`"+home.Display(homeRoot)+"`",
	)
	for name, text := range map[string]string{"About.md": about, "Reference.md": reference} {
		if err := os.WriteFile(filepath.Join(cfg.AtlasVault, name), []byte(r.Replace(text)), 0o644); err != nil {
			return err
		}
	}
	return nil
}
