// Package pages writes the static orientation pages into the atlas vault.
package pages

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/nathanaday/claude-atlas/internal/home"
)

// Repository is the project's home on GitHub.
const Repository = "https://github.com/nathanaday/claude-atlas"

const about = `# About

> [!info] Orientation
> This vault is your atlas: one place that looks across every claude-obsidian vault you keep. claude-atlas generates and maintains it. Source and issues: %REPO%

## What is here

| Page | What it is |
|:--|:--|
| [[Overview]] | The view. Every vault, its heat and idle time, open threads, unfinished work, and your declared priority, side by side. Regenerated by ` + "`claude-atlas refresh`" + `. |
| [[Reference]] | Every ` + "`claude-atlas`" + ` command with examples. |
| ` + "`tree/`" + ` | Your projects. Every markdown file is a project; every folder is a category. Arrange them however you think. |

## How it fits together

| Piece | Where | Who writes it |
|:--|:--|:--|
| Your vaults | ` + "`%VAULTS%`" + ` | claude-obsidian, through Claude Code |
| This atlas | ` + "`%ATLAS%`" + ` | You, in ` + "`tree/`" + `; claude-atlas writes [[Overview]], [[About]], and [[Reference]] |
| Settings and derived state | ` + "`%HOME%`" + ` | claude-atlas. Derived state is rebuilt on every refresh and safe to delete. |

> [!tip] Three rules
> The atlas never writes into a vault. A vault never learns the atlas exists. The atlas never stores a fact it can compute; derived state and [[Overview]] are rebuilt from scratch on every refresh.

## The tree

` + "```" + `
tree/
├── university/
│   └── cs566/
│       ├── capstone.md
│       └── course-material.md
└── personal/
    └── reading-list.md
` + "```" + `

Folders are categories and carry no data of their own; make, rename, and nest them freely. Each markdown file is one project that points at one vault. Move a project by moving its file, then run ` + "`claude-atlas refresh`" + `.

## Editing a project

Open its page under ` + "`tree/`" + `. The properties panel shows the fields the atlas reads:

| Property | Values | Meaning |
|:--|:--|:--|
| vault | a path | The claude-obsidian vault this project tracks. Required. |
| priority | high, normal, low, someday | What you intend, not what you did. |
| state | active, paused, blocked, archived | Where the project stands. |
| blocked_on | free text | What you are waiting for, when state is blocked. |
| review_after | a date | When to revisit these fields. Overview flags it once it passes. |
| purpose, definition_of_done | free text | Why this exists and what finished looks like. |

The body below the properties is yours. Keep notes there that belong to the atlas rather than to the vault.

To add a project by hand, create a markdown file under ` + "`tree/`" + ` with this frontmatter, then refresh:

` + "```yaml" + `
---
schema: atlas.project.v1
vault: /path/to/the/vault
priority: normal
state: active
---
` + "```" + `

Run ` + "`claude-atlas refresh`" + ` after any edit to update [[Overview]].
`

const reference = `# Reference

> [!info] Generated page
> ` + "`claude-atlas`" + ` writes this page on every refresh so it matches the installed version (%VERSION%). Each command sits in its own block so one click copies it.

## Everyday commands

Create a vault. It lands in the vaults directory, the plan is shown, and one confirmation applies it.

` + "```bash" + `
claude-atlas vault new my-project
` + "```" + `

Read every vault and rewrite [[Overview]]. Run it after editing anything under ` + "`tree/`" + `.

` + "```bash" + `
claude-atlas refresh
` + "```" + `

List every project with its heat, priority, and state.

` + "```bash" + `
claude-atlas vault list
` + "```" + `

Show every path and version the atlas uses.

` + "```bash" + `
claude-atlas info
` + "```" + `

## Working in a vault

Start Claude Code inside a vault, then call the wiki skill.

` + "```bash" + `
cd %VAULTS%/my-project && claude
` + "```" + `

` + "```text" + `
/claude-obsidian:wiki
` + "```" + `

## Organizing the tree

The easiest way is in Obsidian. In this vault's file explorer, make folders under ` + "`tree/`" + ` for your categories and drag project pages between them; rename and nest folders as you like. Then refresh.

` + "```bash" + `
claude-atlas refresh
` + "```" + `

The CLI can do the same. File a new project under a category; missing folders are created.

` + "```bash" + `
claude-atlas vault new capstone --category university/cs566
` + "```" + `

Move a project by moving its page.

` + "```bash" + `
mv %ATLAS%/tree/capstone.md %ATLAS%/tree/university/cs566/
` + "```" + `

Register a claude-obsidian vault that already exists.

` + "```bash" + `
claude-atlas vault add ~/Documents/OldVault
` + "```" + `

## Setup and health

Install claude-obsidian into Claude Code, create the atlas, and create a first vault. Safe to run again; finished steps are skipped.

` + "```bash" + `
claude-atlas setup
` + "```" + `

Check the installation and reach every vault.

` + "```bash" + `
claude-atlas doctor
` + "```" + `

` + "```bash" + `
claude-atlas version
` + "```" + `

## Advanced

Set purpose and priority when creating a vault.

` + "```bash" + `
claude-atlas vault new sensor-triage --purpose "Sort field sensor faults." --priority high
` + "```" + `

Create a vault at an explicit path instead of the vaults directory.

` + "```bash" + `
claude-atlas vault new ~/Desktop/scratch-vault
` + "```" + `

Register an existing vault with a display name, a category, and a priority.

` + "```bash" + `
claude-atlas vault add ~/Documents/OldVault --name "Old Vault" --category archive --priority someday
` + "```" + `

Run setup with every location chosen up front.

` + "```bash" + `
claude-atlas setup --atlas-vault ~/Documents/Atlas --vaults-dir ~/Documents/Vaults --first-vault research
` + "```" + `

Run setup without touching Claude Code plugins.

` + "```bash" + `
claude-atlas setup --no-plugin
` + "```" + `

Answer yes to every prompt, for scripts.

` + "```bash" + `
claude-atlas -y setup
` + "```" + `

Use a different home directory for one command.

` + "```bash" + `
claude-atlas --home ~/other-atlas info
` + "```" + `

| Flag or setting | Effect |
|:--|:--|
| ` + "`--home DIR`" + ` | Use a different home instead of ` + "`~/.claude-atlas`" + `. |
| ` + "`-y`, `--yes`" + ` | Answer yes to every prompt. |
| ` + "`CLAUDE_ATLAS_HOME`" + ` | Same as ` + "`--home`" + `, as an environment variable. |
| ` + "`claude_obsidian.path`" + ` in config.json | Use a claude-obsidian checkout instead of the installed plugin. |
`

// Write renders About.md and Reference.md into the atlas vault.
func Write(cfg *home.Config, homeRoot, version string) error {
	r := strings.NewReplacer(
		"%REPO%", Repository,
		"%VERSION%", version,
		"%VAULTS%", home.Display(cfg.VaultsDir),
		"%ATLAS%", home.Display(cfg.AtlasVault),
		"%HOME%", home.Display(homeRoot),
	)
	for name, text := range map[string]string{"About.md": about, "Reference.md": reference} {
		if err := os.WriteFile(filepath.Join(cfg.AtlasVault, name), []byte(r.Replace(text)), 0o644); err != nil {
			return err
		}
	}
	return nil
}
